import type { PatternRule } from '../types';

// 重言・まわりくどい言い回し。suggestを持つ規則は、置換しても文意が変わらない
// ことを条件にしている。判断が分かれるものはseverityをinfoに落とす。
export const redundancyRules: PatternRule[] = [
  {
    id: 'redundancy/suru-koto-ga-dekiru',
    category: 'redundancy',
    severity: 'warning',
    pattern: /することができ(ます|ません|ました|ない|る|た)/g,
    message: '「することができる」は「できる」だけで同じ意味になる',
    suggest: (m) => `でき${m[1] ?? ''}`,
  },
  {
    id: 'redundancy/mazu-saisho',
    category: 'redundancy',
    severity: 'warning',
    pattern: /まず最初に/g,
    message: '「まず」と「最初に」の重言',
    suggest: () => '最初に',
  },
  {
    id: 'redundancy/ichiban-sai',
    category: 'redundancy',
    severity: 'warning',
    pattern: /一番最(初|後)/g,
    message: '「最初」「最後」自体に「一番」の意味が含まれる',
    suggest: (m) => `最${m[1] ?? ''}`,
  },
  {
    id: 'redundancy/atode-koukai',
    category: 'redundancy',
    severity: 'warning',
    pattern: /後で後悔/g,
    message: '「後悔」に「後で」の意味が含まれる',
    suggest: () => '後悔',
  },
  {
    id: 'redundancy/iwakan-kanjiru',
    category: 'redundancy',
    severity: 'warning',
    pattern: /違和感を感じ/g,
    message: '「違和感」と「感じる」の重言。「違和感を覚える」が定着した言い換え',
    suggest: () => '違和感を覚え',
  },
  {
    id: 'redundancy/mada-mi',
    category: 'redundancy',
    severity: 'warning',
    pattern: /まだ未/g,
    message: '「未〜」に「まだ」の意味が含まれる',
    suggest: () => '未',
  },
  {
    id: 'redundancy/kahansuu',
    category: 'redundancy',
    severity: 'warning',
    pattern: /過半数を(超|越)え/g,
    message: '「過半数」に「超える」が含まれる。「半数を超える」か「過半数に達する」へ',
    suggest: (m) => `半数を${m[1] ?? '超'}え`,
  },
  {
    id: 'redundancy/kaku-goto',
    category: 'redundancy',
    severity: 'warning',
    pattern: /各([一-龠々ァ-ヶー]{1,6})ごと/g,
    message: '「各〜」と「ごと」が重複している',
    suggest: (m) => `${m[1] ?? ''}ごと`,
  },
  {
    id: 'redundancy/yaku-hodo',
    category: 'redundancy',
    severity: 'warning',
    pattern: /約([0-9０-９][^。、\sほ]{0,5})ほど/g,
    message: '「約」と「ほど」が重複している',
    suggest: (m) => `約${m[1] ?? ''}`,
  },
  {
    id: 'redundancy/toiu-katachi',
    category: 'redundancy',
    severity: 'info',
    pattern: /という形で/g,
    message: '「という形で」は省くか、具体的な動詞で言い換えられることが多い',
  },
  {
    id: 'redundancy/shitai-to-omoimasu',
    category: 'redundancy',
    severity: 'info',
    pattern: /(し|していき)たいと思います/g,
    message: '意思の表明なら「します」と言い切るほうが明瞭。願望なら「したい」で足りる',
    suggest: (m) => `${m[1] ?? 'し'}ます`,
  },
  {
    id: 'redundancy/dearu-to-ieru',
    category: 'redundancy',
    severity: 'info',
    pattern: /であると(?:言|い)える/g,
    message: '「であると言える」は多くの場合「である」で足りる',
    suggest: () => 'である',
  },
];
